---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(htmltools)
library(sf)
library(leaflet)
library(gt)
library(webshot)
```

```{r}
# roads <- st_read("../data/kx-nashville-tennessee-road-centerlines/nashville-tennessee-road-centerlines.shp", 
#                  as_tibble = T, quiet = T) %>%
#   st_transform('+proj=longlat +datum=WGS84')
# 
# colnames(roads) <-
#   c("transport_edge_id", "st_length", "suffix_dir", "legislation", "is_state_aid",
#     "min_width", "from_maint", "created_user", "last_paved", "is_state_route",
#     "to_maint", "last_edited_date", "condition_date", "pave_group", "verify",
#     "navigable", "max_weight", "abandonment", "row_width", "right_from", "location",
#     "one_way", "pave_length", "update_timestamp", "zip_right", "class", "condition",
#     "accepted_date", "left_from", "warranty_date", "min_height", "driving_time",
#     "suffix_type", "route_name", "former_name", "last_edited_user", "left_to",
#     "usd_gsd", "full_name", "official_status", "easement_ret", "name", "facility_id",
#     "zip_left", "description", "speed_limit", "legislation_2", "user_id", "install_date",
#     "legacy_id", "pm_oci", "prefix_dir", "state_route_no", "description_2", "alt_name",
#     "created_date", "seq_id", "us_route_no", "right_to", "geometry")
# 
# roads <- roads %>%
#   select(transport_edge_id, seq_id, full_name, prefix_dir, name, suffix_type,
#          suffix_dir, from_maint, to_maint, speed_limit, driving_time, class,
#          min_width, st_length)
# 
# interstates <- roads %>% filter(class %in% c(1,2))
# highways <- roads %>% filter(class %in% c(3,4))
# main_roads <- roads %>% filter(class %in% c(5))
# small_roads <- roads %>% filter(class %in% c(6,7))
```

```{r message=FALSE, warning=FALSE}
road_segments <- st_read("../data/Davidson_County data shapefiles/Davidson_Road_Segment_data.shp", 
                         as_tibble = T, quiet = T, ) %>%
  st_transform('+proj=longlat +datum=WGS84') %>%
  filter(!st_is_empty(.)) %>%
  transmute(RD_MSLINK = MSLINK, 
            ID_NUMBER, 
            RD_BLM = BLM,
            RD_ELM = ELM,
            RTE_NME, 
            FUNC_CLASS) %>%
  group_by(ID_NUMBER) %>%
  mutate(RD_SEGMENTS = n(), .after = ID_NUMBER) %>%
  ungroup()

roadway_geometrics <- st_read("../data/Davidson_County data shapefiles/Davidson_Roadway_Geometrics_data.shp",
                              as_tibble = T, quiet = T) %>%
  st_transform('+proj=longlat +datum=WGS84') %>%
  transmute(GEO_MSLINK = MSLINK, 
            ID_NUMBER,
            GEO_BLM = BLM, 
            GEO_ELM = ELM,
            NBR_LANES, 
            THRU_LANES, 
            SPD_LMT, 
            ILLUM, 
            TY_TERRAIN, 
            LAND_USE) %>%
  group_by(ID_NUMBER) %>%
  mutate(GEO_SEGMENTS = n(), .after = ID_NUMBER) %>%
  ungroup()

traffic_segments <- st_read("../data/Davidson_County data shapefiles/Davidson_Traffic_Segment_data.shp", as_tibble = T, quiet = T) %>%
  st_transform('+proj=longlat +datum=WGS84') %>%
  transmute(TR_MSLINK = MSLINK,
            ID_NUMBER,
            TR_BLM = BLM,
            TR_ELM = ELM,
            AADT,
            DHV_PCT,
            PCT_PEAK_H,
            DRCT_DISTR)
```


```{r message=FALSE, warning=FALSE}
roads_1 <- roadway_geometrics %>%
  inner_join(road_segments %>% st_drop_geometry()) %>% 
  filter(GEO_SEGMENTS >= RD_SEGMENTS) %>%
  group_by(GEO_MSLINK) %>%
  slice_min(abs((GEO_BLM + GEO_ELM) / 2 - (RD_BLM + RD_ELM) / 2)) %>%
  ungroup() %>%
  mutate(BLM = GEO_BLM, ELM = GEO_ELM)

roads_2 <- road_segments %>%
  inner_join(roadway_geometrics %>% st_drop_geometry()) %>%
  filter(RD_SEGMENTS > GEO_SEGMENTS) %>%
  group_by(RD_MSLINK) %>%
  slice_min(abs((RD_BLM + RD_ELM) / 2 - (GEO_BLM + GEO_ELM) / 2)) %>%
  ungroup() %>%
  mutate(BLM = RD_BLM, ELM = RD_ELM)

roads <- bind_rows(roads_1, roads_2) %>%
  transmute(ID_NUMBER,
            BLM,
            ELM,
            LENGTH = ELM - BLM,
            RTE_NME,
            FUNC_CLASS,
            NBR_LANES,
            THRU_LANES,
            SPD_LMT,
            ILLUM,
            TY_TERRAIN,
            LAND_USE) %>%
  arrange(ID_NUMBER, BLM, ELM)

roads_final <- roads %>%
  st_drop_geometry() %>%
  inner_join(traffic_segments %>% st_drop_geometry()) %>%
  group_by(ID_NUMBER, BLM, ELM) %>%
  slice_min(abs((BLM + ELM) / 2 - (TR_BLM + TR_ELM) / 2)) %>%
  ungroup() %>%
  right_join(roads) %>%
  select(ID_NUMBER,
         BLM,
         ELM,
         LENGTH,
         RTE_NME,
         FUNC_CLASS,
         NBR_LANES,
         THRU_LANES,
         SPD_LMT,
         ILLUM,
         TY_TERRAIN,
         LAND_USE,
         AADT,
         DHV_PCT,
         PCT_PEAK_H,
         DRCT_DISTR,
         geometry) %>%
  st_sf(sf_column_name = 'geometry')
```

```{r}
accidents_1 <- st_read("../data/traffic_accidents_2021_11_23/geo_export_843312ea-42b0-4c02-a5a6-277108a3e379.shp",
                       as_tibble = T, quiet = T) %>%
  st_transform('+proj=longlat +datum=WGS84') %>%
  filter(!st_is_empty(.)) %>%
  filter(!geometry %in% st_sfc(st_point(c(0, 0)))) %>%
  filter(year(date_date_) == 2014)

accidents_2 <- st_read("../data/traffic_accidents_2022_01_11/geo_export_80ccc574-077c-4ad8-b6d5-668c371ae1f9.shp",
                       as_tibble = T, quiet = T) %>%
  st_transform('+proj=longlat +datum=WGS84') %>%
  filter(!st_is_empty(.)) %>%
  filter(!geometry %in% st_sfc(st_point(c(0, 0)))) %>%
  filter(year(date_date_) < 2022)

accidents <- bind_rows(accidents_1, accidents_2)

colnames(accidents) <-
  c("accident_n", "date", "time", "motor_vehicles_n", "injuries_n", "fatalities_n",
    "property_damage", "hit_and_run", "reporting_officer", "collision_type_code",
    "collision_type_desc", "weather_code", "weather_desc", "illumination_code",
    "illumination_desc", "harmful_code", "harmful_desc", "street_address", "city",
    "state", "zip", "rpa", "precinct", "lat", "long", "geometry")

accidents <- accidents %>%
  mutate(year = year(date),
         month = month(date),
         day = day(date),
         .after = date) %>%
  mutate(injury = injuries_n > 0, .after = injuries_n) %>%
  mutate(hit_and_run = as.logical(hit_and_run)) %>%
  mutate(pedestrian = str_detect(harmful_desc, "PEDESTRIAN"),
         tree = str_detect(harmful_desc, "TREE"),
         animal = str_detect(harmful_desc, paste(c("DEER (ANIMAL)", "OTHER ANIMAL"), collapse = "|")),
         mailbox = str_detect(harmful_desc, "MAIL BOX"),
         .after = hit_and_run)
```

```{r}
nearest <- st_nearest_feature(accidents, roads_final)
accidents_to_roads <- bind_cols(accidents %>% st_drop_geometry(), roads_final[nearest, ])

accidents_by_road <- accidents_to_roads %>% 
  group_by(ID_NUMBER, BLM, ELM, LENGTH) %>%
  summarize(accidents = n(), 
            injury = sum(injury, na.rm = T),
            hit_and_run = sum(hit_and_run, na.rm = T),
            pedestrian = sum(pedestrian, na.rm = T),
            tree = sum(tree, na.rm = T),
            animal = sum(animal, na.rm = T),
            mailbox = sum(mailbox, na.rm = T),
            .groups = "drop") %>%
  mutate(injury_pct = injury / accidents, .after = injury) %>%
  mutate(hit_and_run_pct = hit_and_run / accidents, .after = hit_and_run) %>%
  right_join(roads_final) %>%
  mutate(across(c(accidents, injury, hit_and_run, pedestrian, tree, animal, mailbox),
                ~replace_na(.x, 0))) %>%
  mutate(accident_rate = ((1000000 * accidents) / (365 * 7 * AADT * LENGTH)), .after = accidents) %>%
  st_sf(sf_column_name = 'geometry')
```

```{r}
accidents_by_road$label <-
  paste0("<b>", accidents_by_road$RTE_NME, "</b>",
         "<hr style='margin-top: 2px; margin-bottom: 4px;'>",
         ifelse(test = !is.na(accidents_by_road$AADT), 
                yes = paste0("<b>AADT:</b> ", accidents_by_road$AADT, "<br>",
                             "<b>Accident Rate:</b> ", 
                             round(accidents_by_road$accident_rate, digits = 1), 
                             "<br>"),
                no = ""),
         ifelse(test = accidents_by_road$accidents != 0, 
                yes = paste0("<b>Total Accidents:</b> ", accidents_by_road$accidents, "<br>",
                             "<b>Injury Accidents:</b> ", accidents_by_road$injury, " (", 
                             percent(accidents_by_road$injury_pct, accuracy = 0.1), ")<br>",
                             "<b>Hit-and-Runs:</b> ", accidents_by_road$hit_and_run, " (",
                             percent(accidents_by_road$hit_and_run_pct, accuracy = 0.1), ")<br>",
                             "<b>Pedestrian Collisions:</b> ", accidents_by_road$pedestrian),
                no = paste0("<b>Total Accidents:</b> ", accidents_by_road$accidents, 
                            ifelse(test = !is.na(accidents_by_road$accident_rate), 
                                   yes = paste0(" (", percent(accidents_by_road$accident_rate, accuracy = 0.01), ")<br>"),
                                   no =  "<br>")))) %>% 
  lapply(HTML)
```

```{r}
api_key <- read_json("../data/census.json")
davidson_county_pop_data <- tibble()

for(year in seq(2014, 2019)) {
  census_base_url <- paste0("https://api.census.gov/data/", year, "/acs/acs5")

  census_params <- paste("NAME",
                       "B01001_001E",
                       sep = ",")

  census_query <- list('get' = census_params,
                       'for'= 'county:037',
                       'in' = 'state:47',
                       'key' = api_key)

  census_request <- GET(census_base_url, query = census_query)

  census_data <- fromJSON(content(census_request, as = "text")) %>%
    as_tibble() %>% 
    row_to_names(row_number = 1) %>%    
    transmute(year = year,
              county = NAME,
              population = as.numeric(B01001_001E))

  davidson_county_pop_data <- bind_rows(davidson_county_pop_data, census_data)
}
```

```{r}
api_key <- read_json("../data/census.json")
zip_code_pop_data <- tibble()

for(year in seq(2014, 2019)) {
  census_base_url <- paste0("https://api.census.gov/data/", year, "/acs/acs5")

  census_params <- paste("NAME",
                       "B01001_001E",
                       sep = ",")

  census_query <- list('get' = census_params,
                       'for' = 'zip code tabulation area:*',
                       'in' = 'state:47',
                       'key' = api_key)

  census_request <- GET(census_base_url, query = census_query)

  census_data <- fromJSON(content(census_request, as = "text")) %>%
    as_tibble() %>% 
    row_to_names(row_number = 1) %>% 
    transmute(year = year,
              zipcode = `zip code tabulation area`,
              population = as.numeric(B01001_001E))

  zip_code_pop_data <- bind_rows(zip_code_pop_data, census_data)
}
```

```{r}
zip_codes <- names(table(accidents_to_roads$zip))
p <- zip_code_pop_data %>%
  filter(zipcode %in% zip_codes) %>%
  ggplot(aes(x = year, y = population, color = zipcode, label = zipcode)) +
  geom_line(size = 1.5) +
  theme_bw()

ggplotly(p, tooltip = "label")
```

```{r}
test1 <- zip_code_pop_data %>%
  filter(zipcode %in% zip_codes) %>%
  pivot_wider(id_cols = zipcode, names_from = year, values_from = population) %>%
  mutate(pct_change = `2019`/`2014`)

test2 <- davidson_county_pop_data %>%
  pivot_wider(id_cols = county, names_from = year, values_from = population) %>%
  mutate(pct_change = `2019`/`2014`)
```


```{r}
saveRDS(accidents, "../shiny_app/data/accidents.rds")
saveRDS(roads_final, "../shiny_app/data/roads.rds")
saveRDS(accidents_to_roads, "../shiny_app/data/accidents_to_roads.rds")
saveRDS(accidents_by_road, "../shiny_app/data/accidents_by_road.rds")
saveRDS(davidson_county_pop_data, "~/NSS/projects/nashville-traffic/shiny_app/data/davidson_county_pop_data.rds")
saveRDS(zip_code_pop_data, "~/NSS/projects/nashville-traffic/shiny_app/data/zip_code_pop_data.rds")

```

```{r}
accidents_filtered <- accidents %>%
  sample_n(1000)

accidents_filtered$label <- 
  paste0("<b>Date:</b> ", accidents_filtered$date, "<br>",
         "<b>Time:</b> ", accidents_filtered$time, "<br>", 
         "<b>Street Address:</b> ", accidents_filtered$street_address, "<br>",
         "<b>Harmful Description:</b> ", accidents_filtered$harmful_desc, "<br>",
         "<b>Collision Type Description:</b> ", accidents_filtered$collision_type_desc, "<br>",
         "<b>Number of Vehicles:</b> ", accidents_filtered$motor_vehicles_n, "<br>",
         "<b>Number of Injuries:</b> ", accidents_filtered$injuries_n) %>%
  lapply(htmltools::HTML)

interstates <- accidents_by_road %>% 
  filter(FUNC_CLASS %in% c("R / INTERSTATE", 
                           "U / INTERSTATE", 
                           "U / FWY OR EXP"))

arterial_roads <- accidents_by_road %>% 
  filter(FUNC_CLASS %in% c("R / MIN ART", 
                           "U / MIN ART", 
                           "R / OTH PRIN ART", 
                           "U / MIN ART", 
                           "U OTH PRIN  ART"))

collector_roads <- accidents_by_road %>% 
  filter(FUNC_CLASS %in% c("R / MAJ COL", 
                           "R / MIN COL", 
                           "U / MAJ COL"))

local_roads <- accidents_by_road %>% 
  filter(FUNC_CLASS %in% c("R / LOCAL", 
                           "U / LOCAL"))

map <- leaflet(options = leafletOptions(minZoom = 12, dragging = TRUE)) %>%
  addProviderTiles(provider = "CartoDB.PositronNoLabels") %>%
  setView(lng = -86.7816, lat = 36.1627, zoom = 12) %>%
  setMaxBounds(lng1 = -86.7816 + 1, 
               lat1 = 36.1627 + 1, 
               lng2 = -86.7816 - 1, 
               lat2 = 36.1627 - 1) %>%
  addPolylines(data = local_roads, color = "lightgrey", opacity = 0.75, weight = 0.5, label = ~RTE_NME) %>%
  addPolylines(data = collector_roads, color = "lightgrey", opacity = 1, weight = 0.5, label = ~RTE_NME) %>%
  addPolylines(data = arterial_roads, color = "grey", opacity = 0.5, weight = 1, label = ~RTE_NME) %>%
  addPolylines(data = interstates, color = "#F6CF65", opacity = 0.8, weight = 2, label = ~RTE_NME) %>%
  addCircleMarkers(data = accidents_filtered,
                   weight = 0.5,
                   radius = 2,
                   fillColor = "red",
                   fillOpacity = 0.75,
                   color = "white",
                   label = ~label)

map
```

```{r}
accidents_to_roads %>%
  group_by(Year = as.factor(year)) %>%
  summarize(`Total Accidents` = n(), 
            `Injury Accidents` = sum(injury, na.rm = T), 
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run, na.rm = T), 
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  ggplot(aes(x = Year, y = `Total Accidents`, fill = Year, label = `Total Accidents`)) +
  geom_bar(stat = "identity") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5,  size = 3) +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Spectral")
```

```{r}
accidents_to_roads %>%
  group_by(Year = as.factor(year)) %>%
  summarize(`Total Accidents` = n(), 
            `Injury Accidents` = sum(injury, na.rm = T), 
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run, na.rm = T), 
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  ggplot(aes(x = Year, y = `Injury Accidents`, fill = Year, label = `Injury Accidents`)) +
  geom_bar(stat = "identity") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5,  size = 3) +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Spectral")
```

```{r}
accidents_to_roads %>%
  group_by(Year = as.factor(year)) %>%
  summarize(`Total Accidents` = n(), 
            `Injury Accidents` = sum(injury, na.rm = T), 
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run, na.rm = T), 
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  ggplot(aes(x = Year, y = `Injury Pecentage`, fill = Year, label = percent(`Injury Pecentage`, accuracy = 0.1))) +
  geom_bar(stat = "identity") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5,  size = 3) +
  scale_y_continuous(labels = percent) +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Spectral")
```

```{r}
accidents_to_roads %>%
  group_by(Year = as.factor(year)) %>%
  summarize(`Total Accidents` = n(), 
            `Injury Accidents` = sum(injury, na.rm = T), 
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run, na.rm = T), 
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  ggplot(aes(x = Year, y = `Hit-and-Runs`, fill = Year, label = `Hit-and-Runs`)) +
  geom_bar(stat = "identity") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5,  size = 3) +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Spectral")
```

```{r}
accidents_to_roads %>%
  group_by(Year = as.factor(year)) %>%
  summarize(`Total Accidents` = n(), 
            `Injury Accidents` = sum(injury, na.rm = T), 
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run, na.rm = T), 
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  ggplot(aes(x = Year, y = `Hit-and-Run Pecentage`, fill = Year, label = percent(`Hit-and-Run Pecentage`, accuracy = 0.1))) +
  geom_bar(stat = "identity") +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5,  size = 3) +
  scale_y_continuous(labels = percent) +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Spectral")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  group_by(Road = RTE_NME) %>%
  summarize(`Total Accidents` = sum(accidents, na.rm = T),
            `Injury Accidents` = sum(injury, na.rm = T),
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run),
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(Road, `Total Accidents`) %>%
  arrange(desc(`Total Accidents`)) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_total_accidents.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  transmute(`Road Segment` = RTE_NME,
            `Total Accidents` = accidents,
            `Accident Rate` = `Total Accidents` / `AADT`,
            `Injury Accidents` = injury,
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = hit_and_run,
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(`Road Segment`, `Total Accidents`) %>%
  arrange(desc(`Total Accidents`)) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_segments_total_accidents.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  transmute(`Road Segment` = RTE_NME,
            `Total Accidents` = accidents,
            `Accident Rate` = `Total Accidents` / `AADT`,
            `Injury Accidents` = injury,
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = hit_and_run,
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(`Road Segment`, `Total Accidents`, `Accident Rate`) %>%
  arrange(desc(`Accident Rate`)) %>%
  filter(`Total Accidents` > 15) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_segments_accident_rate.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  group_by(Road = RTE_NME) %>%
  summarize(`Total Accidents` = sum(accidents, na.rm = T),
            `Injury Accidents` = sum(injury, na.rm = T),
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run),
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(Road, `Total Accidents`, `Injury Pecentage`) %>%
  arrange(desc(`Injury Pecentage`)) %>%
  filter(`Total Accidents` > 100) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_injury_pct.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  transmute(`Road Segment` = RTE_NME,
            `Total Accidents` = accidents,
            `Accident Rate` = `Total Accidents` / `AADT`,
            `Injury Accidents` = injury,
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = hit_and_run,
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(`Road Segment`, `Total Accidents`, `Injury Pecentage`) %>%
  arrange(desc(`Injury Pecentage`)) %>%
  filter(`Total Accidents` > 15) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_segments_injury_pct.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  group_by(Road = RTE_NME) %>%
  summarize(`Total Accidents` = sum(accidents, na.rm = T),
            `Injury Accidents` = sum(injury, na.rm = T),
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run),
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(Road, `Total Accidents`, `Hit-and-Run Pecentage`) %>%
  arrange(desc(`Hit-and-Run Pecentage`)) %>%
  filter(`Total Accidents` > 100) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_hit_and_run_pct.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  transmute(`Road Segment` = RTE_NME,
            `Total Accidents` = accidents,
            `Accident Rate` = `Total Accidents` / `AADT`,
            `Injury Accidents` = injury,
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = hit_and_run,
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`) %>%
  select(`Road Segment`, `Total Accidents`, `Hit-and-Run Pecentage`) %>%
  arrange(desc(`Hit-and-Run Pecentage`)) %>%
  filter(`Total Accidents` > 15) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_segments_hit_and_run_pct.png")
```

```{r}
accidents_by_road %>%
  st_drop_geometry() %>%
  group_by(Road = RTE_NME) %>%
  summarize(`Total Accidents` = sum(accidents, na.rm = T),
            `Injury Accidents` = sum(injury, na.rm = T),
            `Injury Pecentage` = `Injury Accidents` / `Total Accidents`,
            `Hit-and-Runs` = sum(hit_and_run),
            `Hit-and-Run Pecentage` = `Hit-and-Runs` / `Total Accidents`,
            `Pedestrian Collisions` = sum(pedestrian)) %>%
  select(Road, `Pedestrian Collisions`) %>%
  arrange(desc(`Pedestrian Collisions`)) %>%
  # filter(`Total Accidents` > 100) %>%
  head(15) %>%
  gt_preview(top_n = 15) %>%
  gtsave("top_roads_pedestrian_collisions.png")
```

```{r}
accidents_to_roads %>% 
  group_by(year) %>% 
  count(month) %>% 
  group_by(month) %>%
  summarize_at(vars(n), list(mean = mean, sd = sd)) %>%
  mutate(month = as.factor(month)) %>%
  ggplot(aes(x = month, y = mean)) + 
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.2)
```

```{r}
accidents_to_roads %>%
  drop_na(injury) %>%
  group_by(month) %>%
  count(injury) %>%
  mutate(month = as.factor(month)) %>%
  ggplot(aes(x = month, y = n, fill = injury)) +
  geom_bar(stat = "identity", position = "fill")
```


```{r}
accidents_to_roads %>%
  drop_na(injury) %>%
  group_by(year, month) %>%
  count(injury) %>%
  group_by(month, injury) %>%
  summarize_at(vars(n), list(mean = mean, sd = sd)) %>%
  mutate(month = as.factor(month)) %>%
  ggplot(aes(x = month, y = mean, ymin = mean - sd, ymax = mean + sd, fill = injury)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3)
```

```{r}
accidents_to_roads %>%
  filter(hit_and_run != "?") %>%
  group_by(month) %>%
  count(hit_and_run) %>%
  mutate(month = as.factor(month)) %>%
  ggplot(aes(x = month, y = n, fill = hit_and_run)) +
  geom_bar(stat = "identity", position = "fill")
```

```{r}
accidents_to_roads %>%
  filter(hit_and_run != "?") %>%
  group_by(year, month) %>%
  count(hit_and_run) %>%
  group_by(month, hit_and_run) %>%
  summarize_at(vars(n), list(mean = mean, sd = sd)) %>%
  mutate(month = as.factor(month)) %>%
  ggplot(aes(x = month, y = mean, ymin = mean - sd, ymax = mean + sd, fill = hit_and_run)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3)
```

```{r}
accidents_to_roads %>%
  drop_na(pedestrian) %>%
  group_by(year) %>%
  summarize(total_accidents = n(), 
            pedestrian_accidents = sum(pedestrian), 
            pedestrian_accident_rate = pedestrian_accidents / total_accidents) %>%
  mutate(year = as.factor(year)) %>%
  ggplot(aes(x = year, y = pedestrian_accident_rate)) +
  geom_bar(stat = "identity")
```


```{r message=FALSE, warning=FALSE}
accidents_to_roads %>%
  group_by(transport_edge_id, full_name, class) %>%
  summarize(accidents = n()) %>%
  arrange(desc(accidents))
```

```{r message=FALSE, warning=FALSE}
accidents_to_roads %>%
  group_by(full_name, class) %>%
  summarize(accidents = n()) %>%
  arrange(desc(accidents))
```

```{r}
accidents_to_roads %>% 
  group_by(full_name) %>%
  summarize(injury_accidents = sum(injury), non_injury_accidents = sum(!injury)) %>%
  mutate(total_accidents = injury_accidents + non_injury_accidents) %>%
  mutate(injury_accident_rate = injury_accidents / total_accidents) %>%
  filter(total_accidents >= 500) %>%
  arrange(desc(injury_accident_rate))
```

```{r}
accidents_to_roads %>% 
  group_by(transport_edge_id, full_name) %>%
  summarize(injury_accidents = sum(injury), non_injury_accidents = sum(!injury)) %>%
  mutate(total_accidents = injury_accidents + non_injury_accidents) %>%
  mutate(injury_accident_rate = injury_accidents / total_accidents) %>%
  filter(total_accidents >= 10) %>%
  arrange(desc(injury_accident_rate))
```

```{r}
accidents_to_roads %>% 
  count(year, sort = F)

accidents_to_roads %>% 
  count(motor_vehicles_n, sort = T)

accidents_to_roads %>% 
  count(injuries_n, sort = T)

accidents_to_roads %>% 
  count(property_damage, sort = T)

accidents_to_roads %>% 
  count(hit_and_run, sort = T)

accidents_to_roads %>% 
  count(collision_type_desc, sort = T)

accidents_to_roads %>% 
  count(weather_desc, sort = T)

accidents_to_roads %>% 
  count(illumination_desc, sort = T)
```

```{r}
pedestrians <- accidents_to_roads[grepl("PEDESTRIAN", accidents_to_roads$harmful_desc), ]

pedestrians %>% 
  count(motor_vehicles_n, sort = T)

pedestrians %>% 
  count(injuries_n, sort = T)

pedestrians %>% 
  count(property_damage, sort = T)

pedestrians %>% 
  count(hit_and_run, sort = T)

pedestrians %>% 
  count(collision_type_desc, sort = T)

pedestrians %>% 
  count(weather_desc, sort = T)

pedestrians %>% 
  count(illumination_desc, sort = T)
```

```{r}
bicyclists <- accidents_to_roads[grepl("PEDALCYCLE", accidents_to_roads$harmful_desc), ]

bicyclists %>% 
  count(motor_vehicles_n, sort = T)

bicyclists %>% 
  count(injuries_n, sort = T)

bicyclists %>% 
  count(property_damage, sort = T)

bicyclists %>% 
  count(hit_and_run, sort = T)

bicyclists %>% 
  count(collision_type_desc, sort = T)

bicyclists %>% 
  count(weather_desc, sort = T)

bicyclists %>% 
  count(illumination_desc, sort = T)
```
